# Generated by Django 5.1.2 on 2024-10-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='usuario', max_length=15),
        ),
    ]
